package matching

import "github.com/guilherme096/data-sync/pkg/data-sync/models"

// ToTableRelation converts a RelationSuggestion to a TableRelation model
func (s *RelationSuggestion) ToTableRelation() *models.TableRelation {
	return &models.TableRelation{
		ID:           "", // Will be generated by storage
		Name:         s.Name,
		LeftTable:    s.LeftTable,
		RightTable:   s.RightTable,
		RelationType: s.RelationType,
		JoinColumn:   s.JoinColumn,
		Description:  s.Description,
	}
}
